{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "CONTRIBUTOR",
   "body" : "Restoring a wallet backup from another chain should result in a dedicated error message (we have _\"Wallet files should not be reused across chains. Restart bitcoind with -walletcrosschain to override.\"_ for that). Unfortunately this is currently not the case for legacy wallet restores, as in the course of cleaning up the newly created wallet directory a `filesystem_error` exception is thrown due to the directory not being empty; the wallet database did indeed load successfully (otherwise we wouldn't know that the chain doesn't match) and hence BDB-related files and directories are already created in the wallet directory.\r\n\r\nFor bitcoind, this leads to a very confusing error message:\r\n```\r\n$ ./src/bitcoin-cli restorewallet test123 ~/.bitcoin/regtest/wallets/regtest_wallet/wallet.dat\r\nerror code: -1\r\nerror message: filesystem error: in remove: Directory not empty [\"/home/thestack/.bitcoin/wallets/test123\"]\r\n```\r\n\r\nEven worse, the GUI crashes in such a scenario:\r\n```\r\nlibc++abi: terminating with uncaught exception of type std::__1::__fs::filesystem::filesystem_error: filesystem error: in remove: Directory not empty [\"/home/thestack/.bitcoin/wallets/foobar\"]\r\nAbort trap (core dumped)\r\n```\r\n\r\nFix this by simply deleting the whole folder via `fs::remove_all`. With this, the expected error message appears both for the `restorewallet` RPC call and in the GUI (as a message-box):\r\n\r\n```\r\n$ ./src/bitcoin-cli restorewallet test123 ~/.bitcoin/regtest/wallets/regtest_wallet/wallet.dat\r\nerror code: -4\r\nerror message:\r\nWallet loading failed. Wallet files should not be reused across chains. Restart bitcoind with -walletcrosschain to override.\r\n```",
   "closed_at" : "2023-01-04T22:46:51Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/3782274?v=4",
      "events_url" : "https://api.github.com/users/achow101/events{/privacy}",
      "followers_url" : "https://api.github.com/users/achow101/followers",
      "following_url" : "https://api.github.com/users/achow101/following{/other_user}",
      "gists_url" : "https://api.github.com/users/achow101/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/achow101",
      "id" : 3782274,
      "login" : "achow101",
      "node_id" : "MDQ6VXNlcjM3ODIyNzQ=",
      "organizations_url" : "https://api.github.com/users/achow101/orgs",
      "received_events_url" : "https://api.github.com/users/achow101/received_events",
      "repos_url" : "https://api.github.com/users/achow101/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/achow101/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/achow101/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/achow101"
   },
   "comments" : 4,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26747/comments",
   "created_at" : "2022-12-23T02:46:18Z",
   "draft" : false,
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26747/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/26747",
   "id" : 1508805584,
   "labels" : [
      {
         "color" : "08a781",
         "default" : false,
         "description" : null,
         "id" : 149424,
         "name" : "Wallet",
         "node_id" : "MDU6TGFiZWwxNDk0MjQ=",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Wallet"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26747/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "PR_kwDOABII585GF3iY",
   "number" : 26747,
   "performed_via_github_app" : null,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/26747.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/26747",
      "merged_at" : "2023-01-04T22:46:51Z",
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/26747.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/26747"
   },
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26747/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26747/timeline",
   "title" : "wallet: fix confusing error / GUI crash on cross-chain legacy wallet restore",
   "updated_at" : "2023-01-04T22:46:52Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26747",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/91535?v=4",
      "events_url" : "https://api.github.com/users/theStack/events{/privacy}",
      "followers_url" : "https://api.github.com/users/theStack/followers",
      "following_url" : "https://api.github.com/users/theStack/following{/other_user}",
      "gists_url" : "https://api.github.com/users/theStack/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/theStack",
      "id" : 91535,
      "login" : "theStack",
      "node_id" : "MDQ6VXNlcjkxNTM1",
      "organizations_url" : "https://api.github.com/users/theStack/orgs",
      "received_events_url" : "https://api.github.com/users/theStack/received_events",
      "repos_url" : "https://api.github.com/users/theStack/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/theStack/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/theStack/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/theStack"
   }
}
