[
   {
      "author_association" : "NONE",
      "body" : "BTW: Bitcoin core version v.0.15.0.0-g3751912e8e\r\nand dmesg shows nothing special related to the Harddisk or the SSD. (no file system errors)",
      "created_at" : "2017-11-07T07:20:22Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-342396644",
      "id" : 342396644,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-11-07T07:30:09Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/342396644",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/15250834?v=4",
         "events_url" : "https://api.github.com/users/kollokollo/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kollokollo/followers",
         "following_url" : "https://api.github.com/users/kollokollo/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kollokollo/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kollokollo",
         "id" : 15250834,
         "login" : "kollokollo",
         "organizations_url" : "https://api.github.com/users/kollokollo/orgs",
         "received_events_url" : "https://api.github.com/users/kollokollo/received_events",
         "repos_url" : "https://api.github.com/users/kollokollo/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kollokollo/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kollokollo/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kollokollo"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "How old were the \"old\" wallets? \r\nDoes the crash only happen on an exit during syncing, or after it has completed?\r\nDoes the corruption disappear if you revert to using a newer wallet?",
      "created_at" : "2017-11-08T03:20:48Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-342698674",
      "id" : 342698674,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-11-08T03:20:48Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/342698674",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/863730?v=4",
         "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
         "followers_url" : "https://api.github.com/users/fanquake/followers",
         "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
         "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/fanquake",
         "id" : 863730,
         "login" : "fanquake",
         "organizations_url" : "https://api.github.com/users/fanquake/orgs",
         "received_events_url" : "https://api.github.com/users/fanquake/received_events",
         "repos_url" : "https://api.github.com/users/fanquake/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/fanquake"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "This isn't a wallet error, its a data-read error which indicates either your disk is silently corrupting data (which can happen without filesystem errors) or your memory is bad/unstable or your CPU is too host/unstable/overclocked. Most common is memory errors or unstable CPU - run memtest and check the temperature of your CPUs under load (eg via linpack or similar load/performance tests)",
      "created_at" : "2017-11-08T04:20:42Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-342706683",
      "id" : 342706683,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-11-08T04:20:42Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/342706683",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/649246?v=4",
         "events_url" : "https://api.github.com/users/TheBlueMatt/events{/privacy}",
         "followers_url" : "https://api.github.com/users/TheBlueMatt/followers",
         "following_url" : "https://api.github.com/users/TheBlueMatt/following{/other_user}",
         "gists_url" : "https://api.github.com/users/TheBlueMatt/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/TheBlueMatt",
         "id" : 649246,
         "login" : "TheBlueMatt",
         "organizations_url" : "https://api.github.com/users/TheBlueMatt/orgs",
         "received_events_url" : "https://api.github.com/users/TheBlueMatt/received_events",
         "repos_url" : "https://api.github.com/users/TheBlueMatt/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/TheBlueMatt/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/TheBlueMatt/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/TheBlueMatt"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "The old wallets were 2011 and 2014. The problem started when I reverted back to the 2017 wallet and is now persistant.\r\nThe Error only appears on an exit. Until then, Bitcoin core runs normally. It appears everytime now on exit. The corruption has not disappeared (using the new wallet now again).\r\n\r\nThe Computer (its a laptop) has never been shut down without having closed bitcoin core. The wallets were exchanged always when bitcoin core was not running.\r\nThe Harddisk nor the SSD (which I use for the chainstate folder) have reported errors. The Laptop is a recent model, I never saw RAM problems. To verify if it was a read error: Which file should I read to test and what against should I compare the content?",
      "created_at" : "2017-11-08T06:47:01Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-342726043",
      "id" : 342726043,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-11-08T06:47:01Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/342726043",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/15250834?v=4",
         "events_url" : "https://api.github.com/users/kollokollo/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kollokollo/followers",
         "following_url" : "https://api.github.com/users/kollokollo/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kollokollo/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kollokollo",
         "id" : 15250834,
         "login" : "kollokollo",
         "organizations_url" : "https://api.github.com/users/kollokollo/orgs",
         "received_events_url" : "https://api.github.com/users/kollokollo/received_events",
         "repos_url" : "https://api.github.com/users/kollokollo/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kollokollo/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kollokollo/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kollokollo"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "BTW: Syncing was complete when the error appeared. The Laptop is an ideapad 110S, max 1 year old, not modified/overclocked or so. Temperature under load was not noticable, however the (external) SSD for the chainstate got quite hot.",
      "created_at" : "2017-11-08T06:48:43Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-342726319",
      "id" : 342726319,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-11-08T06:51:54Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/342726319",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/15250834?v=4",
         "events_url" : "https://api.github.com/users/kollokollo/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kollokollo/followers",
         "following_url" : "https://api.github.com/users/kollokollo/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kollokollo/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kollokollo",
         "id" : 15250834,
         "login" : "kollokollo",
         "organizations_url" : "https://api.github.com/users/kollokollo/orgs",
         "received_events_url" : "https://api.github.com/users/kollokollo/received_events",
         "repos_url" : "https://api.github.com/users/kollokollo/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kollokollo/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kollokollo/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kollokollo"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Here is another symptom: Everytime now bitcoin core is restarted, it starts syncing from Mo, Nov6 8:45, al though the syncing had completed before. If this persists, this would make bitcoin core unusable with time (with the corrupted data).",
      "created_at" : "2017-11-08T06:57:51Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-342727834",
      "id" : 342727834,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-11-09T12:58:10Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/342727834",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/15250834?v=4",
         "events_url" : "https://api.github.com/users/kollokollo/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kollokollo/followers",
         "following_url" : "https://api.github.com/users/kollokollo/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kollokollo/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kollokollo",
         "id" : 15250834,
         "login" : "kollokollo",
         "organizations_url" : "https://api.github.com/users/kollokollo/orgs",
         "received_events_url" : "https://api.github.com/users/kollokollo/received_events",
         "repos_url" : "https://api.github.com/users/kollokollo/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kollokollo/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kollokollo/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kollokollo"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Today I got the following error, during synchronization:\r\n[code]\r\no) warning='1 of last 100 blocks have unexpected version'\r\n2017-11-09 07:52:48 UpdateTip: new best=00000000000000000093ed958fcdee0e7025d7b8d8f15fed221e4c4da32d0369 height=493686 version=0x20000000 log2_work=87.438028 tx=269732432 date='2017-11-08 23:51:00' progress=0.999668 cache=224.6MiB(1705500txo) warning='1 of last 100 blocks have unexpected version'\r\n2017-11-09 07:52:50 LevelDB read failure: Corruption: block checksum mismatch\r\n2017-11-09 07:52:50 Corruption: block checksum mismatch\r\n2017-11-09 07:53:17 Error reading from database: Database corrupted\r\n[/code]\r\n\r\nBitcoin-qt then stopped working (windo not responding anymore). After a while it core-dumped (At least I got the message, that the app has crashed and there is not enough memory to save the core and inform the developpers).\r\nWith the next start, the problem persisted (again not responding) and I had to kill the process with -9. .\r\n\r\n\r\nNo IO-Errors in dmesg.\r\n\r\nSo If this problem is not caused by a bug in bitcoin-qt, how can one fix the database?",
      "created_at" : "2017-11-09T07:55:38Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-343074923",
      "id" : 343074923,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-11-09T08:00:35Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/343074923",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/15250834?v=4",
         "events_url" : "https://api.github.com/users/kollokollo/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kollokollo/followers",
         "following_url" : "https://api.github.com/users/kollokollo/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kollokollo/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kollokollo",
         "id" : 15250834,
         "login" : "kollokollo",
         "organizations_url" : "https://api.github.com/users/kollokollo/orgs",
         "received_events_url" : "https://api.github.com/users/kollokollo/received_events",
         "repos_url" : "https://api.github.com/users/kollokollo/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kollokollo/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kollokollo/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kollokollo"
      }
   },
   {
      "author_association" : "OWNER",
      "body" : "This fortunately has nothing to do with the wallets. Keep a good backup of them. Try syncing them on a different computer.\r\n\r\n> The old wallets were 2011 and 2014. The problem started when I reverted back to the 2017 wallet and is now persistant.\r\n\r\nThe reason for this is likely that part of your blocks or other on-disk state was corrupted, and replacing your wallet triggers a rescan over the blocks from the point it was last used to now, so it was only detected then.",
      "created_at" : "2017-11-09T11:56:22Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-343133242",
      "id" : 343133242,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-11-09T11:56:22Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/343133242",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/126646?v=4",
         "events_url" : "https://api.github.com/users/laanwj/events{/privacy}",
         "followers_url" : "https://api.github.com/users/laanwj/followers",
         "following_url" : "https://api.github.com/users/laanwj/following{/other_user}",
         "gists_url" : "https://api.github.com/users/laanwj/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/laanwj",
         "id" : 126646,
         "login" : "laanwj",
         "organizations_url" : "https://api.github.com/users/laanwj/orgs",
         "received_events_url" : "https://api.github.com/users/laanwj/received_events",
         "repos_url" : "https://api.github.com/users/laanwj/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/laanwj/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/laanwj/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/laanwj"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Well, that might be. All though the rescan was sucessful at least 3 times, until the problems occured after the original wallet was restored, which should not have triggered a rescan (and as far as I remember none has happened). All rescans were done on the same day with more or less the same block and database data. (With wallet I mean only the file wallet.dat). I now also have the suspicion, that the error has nothing to do with the changed wallets. And this because it looks like, that the corruption time was Mo, Nov6 8:45, after any resan, but the same bitcoin-qt session, were the original walled.dat was put back.\r\n\r\nSo: what can I do to repair the corrupted database?",
      "created_at" : "2017-11-09T12:49:15Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-343144759",
      "id" : 343144759,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-11-09T12:49:15Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/343144759",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/15250834?v=4",
         "events_url" : "https://api.github.com/users/kollokollo/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kollokollo/followers",
         "following_url" : "https://api.github.com/users/kollokollo/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kollokollo/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kollokollo",
         "id" : 15250834,
         "login" : "kollokollo",
         "organizations_url" : "https://api.github.com/users/kollokollo/orgs",
         "received_events_url" : "https://api.github.com/users/kollokollo/received_events",
         "repos_url" : "https://api.github.com/users/kollokollo/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kollokollo/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kollokollo/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kollokollo"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I ended up starting from the beginning and reloaded the whole blockchain. This time from a different computer. So far so good, it worked again without problems. \r\nBut then, after importing a single private key (using the console) new strange problems came up:\r\nThe rescanning took a while and finally the bitcoins belonging to the newly imported address were shown in the wallet. BUT: The dates of the transactions belonging to the imported adress where totally messed up. They all show the latest date of the latest transacrion in the wallet, all the same. This is strange. Imagine having a transaction date from yesterday, but 160000 confirmations. So I suggest there is indeed a bug in bitcoin core, which shows up after importing private keys or whole (old) wallets.",
      "created_at" : "2017-11-14T10:02:45Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-344206898",
      "id" : 344206898,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-11-14T10:04:49Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/344206898",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/15250834?v=4",
         "events_url" : "https://api.github.com/users/kollokollo/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kollokollo/followers",
         "following_url" : "https://api.github.com/users/kollokollo/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kollokollo/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kollokollo",
         "id" : 15250834,
         "login" : "kollokollo",
         "organizations_url" : "https://api.github.com/users/kollokollo/orgs",
         "received_events_url" : "https://api.github.com/users/kollokollo/received_events",
         "repos_url" : "https://api.github.com/users/kollokollo/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kollokollo/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kollokollo/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kollokollo"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "@kollokollo the timestamps displayed are the timestamps from the block when the transaction was included, as there is no other way to figure out when a transaction was. It appears the original issue here was a hardware issue, so this should likely be closed. If the transaction timestamps are displaying incorrectly, please open a new issue for that.",
      "created_at" : "2017-11-14T17:54:49Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-344342392",
      "id" : 344342392,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-11-14T17:54:49Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/344342392",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/649246?v=4",
         "events_url" : "https://api.github.com/users/TheBlueMatt/events{/privacy}",
         "followers_url" : "https://api.github.com/users/TheBlueMatt/followers",
         "following_url" : "https://api.github.com/users/TheBlueMatt/following{/other_user}",
         "gists_url" : "https://api.github.com/users/TheBlueMatt/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/TheBlueMatt",
         "id" : 649246,
         "login" : "TheBlueMatt",
         "organizations_url" : "https://api.github.com/users/TheBlueMatt/orgs",
         "received_events_url" : "https://api.github.com/users/TheBlueMatt/received_events",
         "repos_url" : "https://api.github.com/users/TheBlueMatt/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/TheBlueMatt/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/TheBlueMatt/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/TheBlueMatt"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Closing per @TheBlueMatt ",
      "created_at" : "2017-11-14T18:00:08Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-344344029",
      "id" : 344344029,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-11-14T18:00:08Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/344344029",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I always thought, that each block has its individual timestamp, so if you know how many confirmations a tranaction has, you should also know when the transaction happened(+/- 10 min). In my case the timestamps arenot taken from the blocks, but an arbitrary timestamp (from the latest transaction) was taken/shown. Since bitcoin core so far and besides this semms to work normally, I do not care about these old transactions.  But the display of them looks really confusing. (In one case, the recipient of a transaction is shown as (n/a) instead of an adress.) Bitcoin core could do better, since all information should have been retreived correctly during the rescan process.  ",
      "created_at" : "2017-11-15T06:54:46Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-344502602",
      "id" : 344502602,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-11-15T06:54:46Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/344502602",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/15250834?v=4",
         "events_url" : "https://api.github.com/users/kollokollo/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kollokollo/followers",
         "following_url" : "https://api.github.com/users/kollokollo/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kollokollo/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kollokollo",
         "id" : 15250834,
         "login" : "kollokollo",
         "organizations_url" : "https://api.github.com/users/kollokollo/orgs",
         "received_events_url" : "https://api.github.com/users/kollokollo/received_events",
         "repos_url" : "https://api.github.com/users/kollokollo/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kollokollo/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kollokollo/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kollokollo"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "@kollokollo Could you please open a new ticket with more details about these \"strange\" transaction timestamps?",
      "created_at" : "2017-11-15T22:31:35Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-344751053",
      "id" : 344751053,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-11-15T22:31:35Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/344751053",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/649246?v=4",
         "events_url" : "https://api.github.com/users/TheBlueMatt/events{/privacy}",
         "followers_url" : "https://api.github.com/users/TheBlueMatt/followers",
         "following_url" : "https://api.github.com/users/TheBlueMatt/following{/other_user}",
         "gists_url" : "https://api.github.com/users/TheBlueMatt/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/TheBlueMatt",
         "id" : 649246,
         "login" : "TheBlueMatt",
         "organizations_url" : "https://api.github.com/users/TheBlueMatt/orgs",
         "received_events_url" : "https://api.github.com/users/TheBlueMatt/received_events",
         "repos_url" : "https://api.github.com/users/TheBlueMatt/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/TheBlueMatt/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/TheBlueMatt/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/TheBlueMatt"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Issue is opened. Unfortuantely I could not upload the screenshots (using firefox).",
      "created_at" : "2017-11-16T07:38:27Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-344840403",
      "id" : 344840403,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-11-16T07:38:27Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/344840403",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/15250834?v=4",
         "events_url" : "https://api.github.com/users/kollokollo/events{/privacy}",
         "followers_url" : "https://api.github.com/users/kollokollo/followers",
         "following_url" : "https://api.github.com/users/kollokollo/following{/other_user}",
         "gists_url" : "https://api.github.com/users/kollokollo/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/kollokollo",
         "id" : 15250834,
         "login" : "kollokollo",
         "organizations_url" : "https://api.github.com/users/kollokollo/orgs",
         "received_events_url" : "https://api.github.com/users/kollokollo/received_events",
         "repos_url" : "https://api.github.com/users/kollokollo/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/kollokollo/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/kollokollo/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/kollokollo"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I am getting a similar warning since a couple of hours ago. '1 of last 100 bocks have unexpected version'. Any resolution?",
      "created_at" : "2017-12-16T22:26:02Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-352216281",
      "id" : 352216281,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-12-16T22:26:02Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/352216281",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/29265214?v=4",
         "events_url" : "https://api.github.com/users/coralnode/events{/privacy}",
         "followers_url" : "https://api.github.com/users/coralnode/followers",
         "following_url" : "https://api.github.com/users/coralnode/following{/other_user}",
         "gists_url" : "https://api.github.com/users/coralnode/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/coralnode",
         "id" : 29265214,
         "login" : "coralnode",
         "organizations_url" : "https://api.github.com/users/coralnode/orgs",
         "received_events_url" : "https://api.github.com/users/coralnode/received_events",
         "repos_url" : "https://api.github.com/users/coralnode/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/coralnode/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/coralnode/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/coralnode"
      }
   },
   {
      "author_association" : "OWNER",
      "body" : "@coralnode That is unrelated, and completely expected. It's due to a miner using a weird version number in a block, not due to local corruption.",
      "created_at" : "2017-12-16T23:39:07Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-352219823",
      "id" : 352219823,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2017-12-16T23:39:07Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/352219823",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Same problem here\r\nCorruption: block checksum mismatch",
      "created_at" : "2018-01-18T11:53:00Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-358624670",
      "id" : 358624670,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2018-01-18T11:53:00Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/358624670",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/10231165?v=4",
         "events_url" : "https://api.github.com/users/usab/events{/privacy}",
         "followers_url" : "https://api.github.com/users/usab/followers",
         "following_url" : "https://api.github.com/users/usab/following{/other_user}",
         "gists_url" : "https://api.github.com/users/usab/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/usab",
         "id" : 10231165,
         "login" : "usab",
         "organizations_url" : "https://api.github.com/users/usab/orgs",
         "received_events_url" : "https://api.github.com/users/usab/received_events",
         "repos_url" : "https://api.github.com/users/usab/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/usab/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/usab/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/usab"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Please provide hardware information as well as run hardware tests (memtest, linpack/prime95/similar, and a disk SMART check of some kind) when responding to this issue. There are no (known) issues with Bitcoin Core itself which would generate the errors, but there are many examples of unstable hardware which causes them (including hardware which is stable under other workloads).\n\nOn January 18, 2018 11:53:10 AM UTC, usab <notifications@github.com> wrote:\n>Same problem here\n>Corruption: block checksum mismatch\n>\n>-- \n>You are receiving this because you were mentioned.\n>Reply to this email directly or view it on GitHub:\n>https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-358624670\n",
      "created_at" : "2018-01-18T19:56:46Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/11627#issuecomment-358763360",
      "id" : 358763360,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11627",
      "updated_at" : "2018-01-18T19:56:46Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/358763360",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/649246?v=4",
         "events_url" : "https://api.github.com/users/TheBlueMatt/events{/privacy}",
         "followers_url" : "https://api.github.com/users/TheBlueMatt/followers",
         "following_url" : "https://api.github.com/users/TheBlueMatt/following{/other_user}",
         "gists_url" : "https://api.github.com/users/TheBlueMatt/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/TheBlueMatt",
         "id" : 649246,
         "login" : "TheBlueMatt",
         "organizations_url" : "https://api.github.com/users/TheBlueMatt/orgs",
         "received_events_url" : "https://api.github.com/users/TheBlueMatt/received_events",
         "repos_url" : "https://api.github.com/users/TheBlueMatt/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/TheBlueMatt/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/TheBlueMatt/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/TheBlueMatt"
      }
   }
]
