[
   {
      "author_association" : "MEMBER",
      "body" : "Can you run with `-debug=leveldb` and provide more verbose error messages? I'm also interested in seeing a copy of the corrupted table file. The name of the corrupted file should be in the logs when you use `-debug=leveldb`\r\n\r\nTo actually proceed with syncing you'll need to run with `-reindex` to rebuild your local copy of the utxo database. This will take a long time because it has to reprocess old blocks, but it won't re-download any blocks you already have locally.",
      "created_at" : "2018-03-09T23:07:01Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/12628#issuecomment-371970987",
      "id" : 371970987,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/12628",
      "updated_at" : "2018-03-10T07:05:19Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/371970987",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/2734?v=4",
         "events_url" : "https://api.github.com/users/eklitzke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/eklitzke/followers",
         "following_url" : "https://api.github.com/users/eklitzke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/eklitzke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/eklitzke",
         "id" : 2734,
         "login" : "eklitzke",
         "organizations_url" : "https://api.github.com/users/eklitzke/orgs",
         "received_events_url" : "https://api.github.com/users/eklitzke/received_events",
         "repos_url" : "https://api.github.com/users/eklitzke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/eklitzke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/eklitzke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/eklitzke"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Hi @eklitzke and thanks for your interest in solving my issue. Apologies for the delay, I saved the entire folder containing the files producing this error so I could get back to it at a later stage but in the meanwhile I synced from scratch importing the private keys to a new wallet that is now running fine.\r\n\r\nI have now forced the client to use this corrupt data directory because I hope that my experience will help solving the issue that could occur to others.\r\n\r\nI have therefore run the client as you suggested with -debug=leveldb and here are the error messages obtained this time:\r\n\r\n[debug.log](https://github.com/bitcoin/bitcoin/files/1844934/debug.log)\r\n\r\ndb.log that is referenced to is totally blank, no information at all.\r\n\r\nI can see that it makes a reference to .dat files, please let me know which one you would like to analyze and I will happily upload it for you.\r\n\r\nMany thanks ",
      "created_at" : "2018-03-25T01:18:26Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/12628#issuecomment-375937842",
      "id" : 375937842,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/12628",
      "updated_at" : "2018-03-25T01:24:24Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/375937842",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/7671309?v=4",
         "events_url" : "https://api.github.com/users/fabioganga/events{/privacy}",
         "followers_url" : "https://api.github.com/users/fabioganga/followers",
         "following_url" : "https://api.github.com/users/fabioganga/following{/other_user}",
         "gists_url" : "https://api.github.com/users/fabioganga/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/fabioganga",
         "id" : 7671309,
         "login" : "fabioganga",
         "organizations_url" : "https://api.github.com/users/fabioganga/orgs",
         "received_events_url" : "https://api.github.com/users/fabioganga/received_events",
         "repos_url" : "https://api.github.com/users/fabioganga/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/fabioganga/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/fabioganga/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/fabioganga"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "I have some notes in #12690 about LeveLDB corruption, but this seems to be a separate issue. The error message \"block checksum mismatch\" implies that LevelDB handed out data with checksum X to the kernel, but then later read that data back with checksum Y. That could be bad hardware, a bad filesystem, or anywhere in-between. But I don't think it's a bug in Bitcoin (or LevelDB).",
      "created_at" : "2018-03-27T08:07:14Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/12628#issuecomment-376434604",
      "id" : 376434604,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/12628",
      "updated_at" : "2018-03-27T08:07:14Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/376434604",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/2734?v=4",
         "events_url" : "https://api.github.com/users/eklitzke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/eklitzke/followers",
         "following_url" : "https://api.github.com/users/eklitzke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/eklitzke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/eklitzke",
         "id" : 2734,
         "login" : "eklitzke",
         "organizations_url" : "https://api.github.com/users/eklitzke/orgs",
         "received_events_url" : "https://api.github.com/users/eklitzke/received_events",
         "repos_url" : "https://api.github.com/users/eklitzke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/eklitzke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/eklitzke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/eklitzke"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "If such things (levelDB issues) can happen on machines not overheating, not having faulty disks or faulty RAM, then why isn't bitcoind more resilient? Another charged particle can ruin your day...\r\nDo we need to move to ECC and get some RAM-producer's stawks? Or will there be a software workaround?",
      "created_at" : "2019-09-30T12:10:18Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/12628#issuecomment-536532777",
      "id" : 536532777,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/12628",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDUzNjUzMjc3Nw==",
      "updated_at" : "2019-09-30T12:10:18Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/536532777",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/5012213?v=4",
         "events_url" : "https://api.github.com/users/udovdh/events{/privacy}",
         "followers_url" : "https://api.github.com/users/udovdh/followers",
         "following_url" : "https://api.github.com/users/udovdh/following{/other_user}",
         "gists_url" : "https://api.github.com/users/udovdh/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/udovdh",
         "id" : 5012213,
         "login" : "udovdh",
         "node_id" : "MDQ6VXNlcjUwMTIyMTM=",
         "organizations_url" : "https://api.github.com/users/udovdh/orgs",
         "received_events_url" : "https://api.github.com/users/udovdh/received_events",
         "repos_url" : "https://api.github.com/users/udovdh/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/udovdh/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/udovdh/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/udovdh"
      }
   }
]
