{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "MEMBER",
   "body" : "`wallet_send.py --legacy-wallet` line 332\r\n\r\nhttps://cirrus-ci.com/task/6260771733635072\r\n\r\n```\r\n2022-01-25T13:05:06.243000Z TestFramework (INFO): Test setting explicit fee rate\r\n2022-01-25T13:05:06.666000Z TestFramework (ERROR): Assertion failed\r\nTraceback (most recent call last):\r\n  File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py\", line 132, in main\r\n    self.run_test()\r\n  File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_send.py\", line 332, in run_test\r\n    assert_fee_amount(fee, Decimal(len(res[\"hex\"]) / 2), Decimal(\"0.00004531\"))\r\n  File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py\", line 45, in assert_fee_amount\r\n    raise AssertionError(\"Fee of %s BTC too high! (Should be %s BTC)\" % (str(fee), str(target_fee)))\r\nAssertionError: Fee of 0.00000993 BTC too high! (Should be 0.00000983 BTC)\r\n```\r\n\r\nHaven't seen it fail yet locally on the same branch while running:\r\n```\r\n(for i in {1..1000}; do test/functional/wallet_send.py --legacy-wallet --pdbonfailure ; done)\r\n```\r\n\r\nThis test assertion was added in October 2020 (603c0050837) and the `get_fee()` test utility helper in October 2021 (80dc829be7f), so if the error is new then it might stem from a more recent change.",
   "closed_at" : "2022-04-25T08:55:11Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/863730?v=4",
      "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
      "followers_url" : "https://api.github.com/users/fanquake/followers",
      "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
      "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/fanquake",
      "id" : 863730,
      "login" : "fanquake",
      "node_id" : "MDQ6VXNlcjg2MzczMA==",
      "organizations_url" : "https://api.github.com/users/fanquake/orgs",
      "received_events_url" : "https://api.github.com/users/fanquake/received_events",
      "repos_url" : "https://api.github.com/users/fanquake/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/fanquake"
   },
   "comments" : 16,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/24151/comments",
   "created_at" : "2022-01-25T13:39:11Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/24151/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/24151",
   "id" : 1113901630,
   "labels" : [
      {
         "color" : "FBBAAB",
         "default" : false,
         "description" : null,
         "id" : 64585,
         "name" : "Bug",
         "node_id" : "MDU6TGFiZWw2NDU4NQ==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug"
      },
      {
         "color" : "d4c5f9",
         "default" : false,
         "description" : null,
         "id" : 62963516,
         "name" : "Tests",
         "node_id" : "MDU6TGFiZWw2Mjk2MzUxNg==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/24151/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "I_kwDOABII585CZMo-",
   "number" : 24151,
   "performed_via_github_app" : null,
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/24151/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/24151/timeline",
   "title" : "\"Fee too high\" CI error in wallet_send.py",
   "updated_at" : "2022-04-25T08:55:11Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/24151",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/2415484?v=4",
      "events_url" : "https://api.github.com/users/jonatack/events{/privacy}",
      "followers_url" : "https://api.github.com/users/jonatack/followers",
      "following_url" : "https://api.github.com/users/jonatack/following{/other_user}",
      "gists_url" : "https://api.github.com/users/jonatack/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/jonatack",
      "id" : 2415484,
      "login" : "jonatack",
      "node_id" : "MDQ6VXNlcjI0MTU0ODQ=",
      "organizations_url" : "https://api.github.com/users/jonatack/orgs",
      "received_events_url" : "https://api.github.com/users/jonatack/received_events",
      "repos_url" : "https://api.github.com/users/jonatack/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/jonatack/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/jonatack/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/jonatack"
   }
}
