[
   {
      "author_association" : "MEMBER",
      "body" : "When did this issue first occur?\r\n\r\nPlease check your debug.log for possible causes; Alternatively you can upload it here.\r\n\r\nYou can find the debug.log in your [data dir](https://github.com/bitcoin/bitcoin/blob/master/doc/files.md#data-directory-location).\r\n\r\nPlease be aware that the debug log might contain personally identifying information.",
      "created_at" : "2022-09-13T07:38:21Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26072#issuecomment-1245019920",
      "id" : 1245019920,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26072",
      "node_id" : "IC_kwDOABII585KNX8Q",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1245019920/reactions"
      },
      "updated_at" : "2022-09-13T07:38:21Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1245019920",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I have already looked at my log. It's an Error where 40 files are missing. This happen a few days ago. \n\nSo I'm trying to repare it from where it left off. But the question is how long will it take to repare?? ",
      "created_at" : "2022-09-13T07:59:30Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26072#issuecomment-1245041581",
      "id" : 1245041581,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26072",
      "node_id" : "IC_kwDOABII585KNdOt",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1245041581/reactions"
      },
      "updated_at" : "2022-09-13T07:59:30Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1245041581",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/70559445?v=4",
         "events_url" : "https://api.github.com/users/Rlavington/events{/privacy}",
         "followers_url" : "https://api.github.com/users/Rlavington/followers",
         "following_url" : "https://api.github.com/users/Rlavington/following{/other_user}",
         "gists_url" : "https://api.github.com/users/Rlavington/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/Rlavington",
         "id" : 70559445,
         "login" : "Rlavington",
         "node_id" : "MDQ6VXNlcjcwNTU5NDQ1",
         "organizations_url" : "https://api.github.com/users/Rlavington/orgs",
         "received_events_url" : "https://api.github.com/users/Rlavington/received_events",
         "repos_url" : "https://api.github.com/users/Rlavington/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/Rlavington/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/Rlavington/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/Rlavington"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Do you mind sharing your `debug.log` though? It would be helpful to debug your situation.\r\nAlso, was your node fully synced before running into this problem? ",
      "created_at" : "2022-09-13T17:21:22Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26072#issuecomment-1245714537",
      "id" : 1245714537,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26072",
      "node_id" : "IC_kwDOABII585KQBhp",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1245714537/reactions"
      },
      "updated_at" : "2022-09-13T17:21:22Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1245714537",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/22493292?v=4",
         "events_url" : "https://api.github.com/users/aureleoules/events{/privacy}",
         "followers_url" : "https://api.github.com/users/aureleoules/followers",
         "following_url" : "https://api.github.com/users/aureleoules/following{/other_user}",
         "gists_url" : "https://api.github.com/users/aureleoules/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/aureleoules",
         "id" : 22493292,
         "login" : "aureleoules",
         "node_id" : "MDQ6VXNlcjIyNDkzMjky",
         "organizations_url" : "https://api.github.com/users/aureleoules/orgs",
         "received_events_url" : "https://api.github.com/users/aureleoules/received_events",
         "repos_url" : "https://api.github.com/users/aureleoules/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/aureleoules/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/aureleoules/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/aureleoules"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "> Do you mind sharing your `debug.log` though? It would be helpful to debug your situation.\n> Also, was your node fully synced before running into this problem? \n\n\nError:\n\n2022-09-08T05:53:01Z Fatal LevelDB error: Corruption: 40 missing files; e.g.: C:\\Users\\ozlav.DESKTOP-PQL90HA\\AppData\\Roaming\\Bitcoin\\chainstate\n\nThere, it lost 40 files some how??\n\nYes I was fully synced up and work fine for a few days before this happened. ",
      "created_at" : "2022-09-13T21:28:00Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26072#issuecomment-1245971646",
      "id" : 1245971646,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26072",
      "node_id" : "IC_kwDOABII585KRAS-",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1245971646/reactions"
      },
      "updated_at" : "2022-09-13T21:28:00Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1245971646",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/70559445?v=4",
         "events_url" : "https://api.github.com/users/Rlavington/events{/privacy}",
         "followers_url" : "https://api.github.com/users/Rlavington/followers",
         "following_url" : "https://api.github.com/users/Rlavington/following{/other_user}",
         "gists_url" : "https://api.github.com/users/Rlavington/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/Rlavington",
         "id" : 70559445,
         "login" : "Rlavington",
         "node_id" : "MDQ6VXNlcjcwNTU5NDQ1",
         "organizations_url" : "https://api.github.com/users/Rlavington/orgs",
         "received_events_url" : "https://api.github.com/users/Rlavington/received_events",
         "repos_url" : "https://api.github.com/users/Rlavington/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/Rlavington/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/Rlavington/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/Rlavington"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "This issue looks like a continuation of #26042 after applying of https://github.com/bitcoin/bitcoin/issues/26042#issuecomment-1240707358:\r\n\r\n> **Describe the solution you'd like**\r\n> \r\n> I have already \"reindex-chainstate\" in command prompt.\r\n> \r\n> To rebuild the blockchain from where the error occurred.\r\n> \r\n> **Describe alternatives you've considered**\r\n> \r\n> I have already \"reindex-chainstate\" in command prompt.\r\n\r\n",
      "created_at" : "2022-09-13T21:49:29Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26072#issuecomment-1245987264",
      "id" : 1245987264,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26072",
      "node_id" : "IC_kwDOABII585KREHA",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1245987264/reactions"
      },
      "updated_at" : "2022-09-13T21:49:29Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1245987264",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/32963518?v=4",
         "events_url" : "https://api.github.com/users/hebasto/events{/privacy}",
         "followers_url" : "https://api.github.com/users/hebasto/followers",
         "following_url" : "https://api.github.com/users/hebasto/following{/other_user}",
         "gists_url" : "https://api.github.com/users/hebasto/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/hebasto",
         "id" : 32963518,
         "login" : "hebasto",
         "node_id" : "MDQ6VXNlcjMyOTYzNTE4",
         "organizations_url" : "https://api.github.com/users/hebasto/orgs",
         "received_events_url" : "https://api.github.com/users/hebasto/received_events",
         "repos_url" : "https://api.github.com/users/hebasto/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/hebasto/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/hebasto/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/hebasto"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Just an update date on how it all went. I had to delete all of the blocks. \n\nThen just by change the Bitcoincore version 24.0 became available.\n\nI download the new version 24.0 then I had to re-sync it all again. \n\nNow it works. \n\nAlso made a back on my portable HDD. ",
      "created_at" : "2022-12-21T04:15:01Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26072#issuecomment-1360834031",
      "id" : 1360834031,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26072",
      "node_id" : "IC_kwDOABII585RHK3v",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1360834031/reactions"
      },
      "updated_at" : "2022-12-21T04:15:01Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1360834031",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/70559445?v=4",
         "events_url" : "https://api.github.com/users/Rlavington/events{/privacy}",
         "followers_url" : "https://api.github.com/users/Rlavington/followers",
         "following_url" : "https://api.github.com/users/Rlavington/following{/other_user}",
         "gists_url" : "https://api.github.com/users/Rlavington/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/Rlavington",
         "id" : 70559445,
         "login" : "Rlavington",
         "node_id" : "MDQ6VXNlcjcwNTU5NDQ1",
         "organizations_url" : "https://api.github.com/users/Rlavington/orgs",
         "received_events_url" : "https://api.github.com/users/Rlavington/received_events",
         "repos_url" : "https://api.github.com/users/Rlavington/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/Rlavington/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/Rlavington/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/Rlavington"
      }
   }
]
