{
   "assignee" : null,
   "assignees" : [],
   "author_association" : "NONE",
   "body" : "<!-- This issue tracker is only for technical issues related to Bitcoin Core.\r\n\r\nGeneral bitcoin questions and/or support requests are best directed to the Bitcoin StackExchange at https://bitcoin.stackexchange.com.\r\n\r\nFor reporting security issues, please read instructions at https://bitcoincore.org/en/contact/.\r\n\r\nIf the node is \"stuck\" during sync or giving \"block checksum mismatch\" errors, please ensure your hardware is stable by running memtest and observe CPU temperature with a load-test tool such as linpack before creating an issue! -->\r\n\r\n<!-- Describe the issue -->\r\n\r\n<!--- What behavior did you expect? -->\r\n\r\n<!--- What was the actual behavior (provide screenshots if the issue is GUI-related)? -->\r\n```\r\n...\r\nRunning tests: flatfile_tests from ../../src/test/flatfile_tests.cpp\r\nRunning tests: fs_tests from ../../src/test/fs_tests.cpp\r\nRunning tests: getarg_tests from ../../src/test/getarg_tests.cpp\r\nRunning 1 test case...\r\nEntering test module \"Bitcoin Core Test Suite\"\r\n../../src/test/fs_tests.cpp(11): Entering test suite \"fs_tests\"\r\n../../src/test/fs_tests.cpp(13): Entering test case \"fsbridge_fstream\"\r\nunknown location(0): fatal error: in \"fs_tests/fsbridge_fstream\": boost::system::system_error: boost::filesystem::path codecvt to string: error\r\n../../src/test/fs_tests.cpp(13): last checkpoint: \"fsbridge_fstream\" entry.\r\n../../src/test/fs_tests.cpp(13): Leaving test case \"fsbridge_fstream\"; testing time: 40255us\r\n../../src/test/fs_tests.cpp(11): Leaving test suite \"fs_tests\"; testing time: 40286us\r\nLeaving test module \"Bitcoin Core Test Suite\"; testing time: 40445us\r\n\r\n*** 1 failure is detected in the test module \"Bitcoin Core Test Suite\"\r\nMakefile:13625: recipe for target 'test/fs_tests.cpp.test' failed\r\nmake[3]: *** [test/fs_tests.cpp.test] Error 1\r\n...\r\n```\r\n<!--- How reliably can you reproduce the issue, what are the steps to do so? -->\r\nThis is a fresh clone, run with `../configure --disable-ccache --with-incompatible-bdb` under a build/ subdirectory. Running `make check`, `make -j4 check` both produce this issue.\r\n\r\n<!-- What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)? -->\r\nRunning off fresh master (commit 1088b90cbae3e9e9fe686356361f1ce08ad8a478)\r\n\r\n<!-- What type of machine are you observing the error on (OS/CPU and disk type)? -->\r\nDebian GNU/Linux 9.9 (stretch) ; Xeon E5-2630L on VPS.\r\nlibboost-filesystem version is 1.67.0-7~bpo9+1",
   "closed_at" : "2019-07-05T02:41:02Z",
   "closed_by" : {
      "avatar_url" : "https://avatars0.githubusercontent.com/u/36528214?v=4",
      "events_url" : "https://api.github.com/users/markblundeberg/events{/privacy}",
      "followers_url" : "https://api.github.com/users/markblundeberg/followers",
      "following_url" : "https://api.github.com/users/markblundeberg/following{/other_user}",
      "gists_url" : "https://api.github.com/users/markblundeberg/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/markblundeberg",
      "id" : 36528214,
      "login" : "markblundeberg",
      "node_id" : "MDQ6VXNlcjM2NTI4MjE0",
      "organizations_url" : "https://api.github.com/users/markblundeberg/orgs",
      "received_events_url" : "https://api.github.com/users/markblundeberg/received_events",
      "repos_url" : "https://api.github.com/users/markblundeberg/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/markblundeberg/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/markblundeberg/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/markblundeberg"
   },
   "comments" : 2,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16340/comments",
   "created_at" : "2019-07-05T02:19:53Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16340/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/16340",
   "id" : 464434534,
   "labels" : [
      {
         "color" : "d4c5f9",
         "default" : false,
         "id" : 62963516,
         "name" : "Tests",
         "node_id" : "MDU6TGFiZWw2Mjk2MzUxNg==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16340/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "MDU6SXNzdWU0NjQ0MzQ1MzQ=",
   "number" : 16340,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "fs_tests fail Debian 9",
   "updated_at" : "2019-07-05T02:41:02Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16340",
   "user" : {
      "avatar_url" : "https://avatars0.githubusercontent.com/u/36528214?v=4",
      "events_url" : "https://api.github.com/users/markblundeberg/events{/privacy}",
      "followers_url" : "https://api.github.com/users/markblundeberg/followers",
      "following_url" : "https://api.github.com/users/markblundeberg/following{/other_user}",
      "gists_url" : "https://api.github.com/users/markblundeberg/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/markblundeberg",
      "id" : 36528214,
      "login" : "markblundeberg",
      "node_id" : "MDQ6VXNlcjM2NTI4MjE0",
      "organizations_url" : "https://api.github.com/users/markblundeberg/orgs",
      "received_events_url" : "https://api.github.com/users/markblundeberg/received_events",
      "repos_url" : "https://api.github.com/users/markblundeberg/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/markblundeberg/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/markblundeberg/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/markblundeberg"
   }
}
