{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "CONTRIBUTOR",
   "body" : "`Win64 native [vs2022]` CI check in  https://github.com/bitcoin/bitcoin/pull/25747 generated the error:\r\n\r\n```\r\n183/246 - wallet_encryption.py --descriptors failed, Duration: 7 s\r\nstdout:\r\n2022-07-31T03:33:43.922000Z TestFramework (INFO): Initializing test directory C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\test_runner_â¿_ð_20220731_024158\\wallet_encryption_65\r\n2022-07-31T03:33:49.648000Z TestFramework (INFO): Check a timeout less than the limit\r\n2022-07-31T03:33:49.821000Z TestFramework (INFO): Check a timeout greater than the limit\r\n2022-07-31T03:33:49.993000Z TestFramework (ERROR): Assertion failed\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\test_framework\\test_framework.py\", line 133, in main\r\n    self.run_test()\r\n  File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\wallet_encryption.py\", line 93, in run_test\r\n    assert_greater_than(expected_time_with_buffer, actual_time)\r\n  File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\test_framework\\util.py\", line 57, in assert_greater_than\r\n    raise AssertionError(\"%s <= %s\" % (str(thing1), str(thing2)))\r\nAssertionError: 1759238429.9936483 <= 1759238430\r\n```\r\n\r\nThe error seems related to floating point precision `AssertionError: 1759238429.9936483 <= 1759238430` or something intermittent.\r\n\r\nhttps://cirrus-ci.com/task/5935928832163840",
   "closed_at" : "2022-07-31T10:46:17Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/863730?v=4",
      "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
      "followers_url" : "https://api.github.com/users/fanquake/followers",
      "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
      "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/fanquake",
      "id" : 863730,
      "login" : "fanquake",
      "node_id" : "MDQ6VXNlcjg2MzczMA==",
      "organizations_url" : "https://api.github.com/users/fanquake/orgs",
      "received_events_url" : "https://api.github.com/users/fanquake/received_events",
      "repos_url" : "https://api.github.com/users/fanquake/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/fanquake"
   },
   "comments" : 1,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25758/comments",
   "created_at" : "2022-07-31T05:57:16Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25758/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/25758",
   "id" : 1323370436,
   "labels" : [
      {
         "color" : "d4c5f9",
         "default" : false,
         "description" : null,
         "id" : 62963516,
         "name" : "Tests",
         "node_id" : "MDU6TGFiZWw2Mjk2MzUxNg==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25758/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "I_kwDOABII585O4QfE",
   "number" : 25758,
   "performed_via_github_app" : null,
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25758/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "state_reason" : "completed",
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25758/timeline",
   "title" : "ci: `AssertionError: 1759238429.9936483` <= 1759238430 in `wallet_encryption.py --descriptors`",
   "updated_at" : "2022-07-31T10:46:24Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25758",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/94266259?v=4",
      "events_url" : "https://api.github.com/users/w0xlt/events{/privacy}",
      "followers_url" : "https://api.github.com/users/w0xlt/followers",
      "following_url" : "https://api.github.com/users/w0xlt/following{/other_user}",
      "gists_url" : "https://api.github.com/users/w0xlt/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/w0xlt",
      "id" : 94266259,
      "login" : "w0xlt",
      "node_id" : "U_kgDOBZ5jkw",
      "organizations_url" : "https://api.github.com/users/w0xlt/orgs",
      "received_events_url" : "https://api.github.com/users/w0xlt/received_events",
      "repos_url" : "https://api.github.com/users/w0xlt/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/w0xlt/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/w0xlt/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/w0xlt"
   }
}
