{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "CONTRIBUTOR",
   "body" : "Intermittent CI failure in `p2p_compactblocks.py`:\r\n\r\n```\r\n test  2021-05-15T12:59:56.247000Z TestFramework.p2p (DEBUG): Received message from 127.0.0.1:16352: msg_ping(nonce=7cb20024846796fe) \r\n test  2021-05-15T12:59:56.247000Z TestFramework.p2p (DEBUG): Send message to 127.0.0.1:16352: msg_pong(nonce=7cb20024846796fe) \r\n node0 2021-05-15T12:59:56.249511Z [msghand] [net_processing.cpp:2339] [ProcessMessage] received: pong (8 bytes) peer=0 \r\n node0 2021-05-15T12:59:56.249898Z [msghand] [net_processing.cpp:2339] [ProcessMessage] received: pong (8 bytes) peer=1 \r\n test  2021-05-15T12:59:56.351000Z TestFramework.p2p (DEBUG): Received message from 127.0.0.1:16352: msg_ping(nonce=7a8ccde9e7d59f55) \r\n test  2021-05-15T12:59:56.351000Z TestFramework.p2p (DEBUG): Send message to 127.0.0.1:16352: msg_pong(nonce=7a8ccde9e7d59f55) \r\n node0 2021-05-15T12:59:56.351164Z [msghand] [net.cpp:2968] [PushMessage] sending ping (8 bytes) peer=2 \r\n node0 2021-05-15T12:59:56.359345Z [msghand] [net_processing.cpp:2339] [ProcessMessage] received: pong (8 bytes) peer=2 \r\n node0 2021-05-15T12:59:56.765182Z [scheduler] [random.cpp:523] [SeedPeriodic] Feeding 32769 bytes of dynamic environment data into RNG \r\n node0 2021-05-15T13:00:56.928013Z [scheduler] [random.cpp:523] [SeedPeriodic] Feeding 32774 bytes of dynamic environment data into RNG \r\n test  2021-05-15T13:01:09.354000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: '''' \r\n                                           def test_function():\r\n                                               if check_connected:\r\n                                                   assert self.is_connected\r\n                                               return test_function_in()\r\n                                   '''\r\n test  2021-05-15T13:01:09.366000Z TestFramework (ERROR): Assertion failed \r\n                                   Traceback (most recent call last):\r\n                                     File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py\", line 128, in main\r\n                                       self.run_test()\r\n                                     File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/p2p_compactblocks.py\", line 844, in run_test\r\n                                       self.test_end_to_end_block_relay([self.segwit_node, self.old_node])\r\n                                     File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/p2p_compactblocks.py\", line 675, in test_end_to_end_block_relay\r\n                                       l.wait_until(lambda: \"cmpctblock\" in l.last_message, timeout=30)\r\n                                     File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/p2p.py\", line 450, in wait_until\r\n                                       wait_until_helper(test_function, timeout=timeout, lock=p2p_lock, timeout_factor=self.timeout_factor)\r\n                                     File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py\", line 261, in wait_until_helper\r\n                                       raise AssertionError(\"Predicate {} not true after {} seconds\".format(predicate_source, timeout))\r\n                                   AssertionError: Predicate ''''\r\n                                           def test_function():\r\n                                               if check_connected:\r\n                                                   assert self.is_connected\r\n                                               return test_function_in()\r\n                                   ''' not true after 1200.0 seconds\r\nâ¦\r\np2p_compactblocks.py                               | â Failed  | 1278 s\r\n```\r\n\r\nSee Cirrus CI log for details: https://cirrus-ci.com/task/4959275735842816",
   "closed_at" : "2021-05-17T00:35:54Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/863730?v=4",
      "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
      "followers_url" : "https://api.github.com/users/fanquake/followers",
      "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
      "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/fanquake",
      "id" : 863730,
      "login" : "fanquake",
      "node_id" : "MDQ6VXNlcjg2MzczMA==",
      "organizations_url" : "https://api.github.com/users/fanquake/orgs",
      "received_events_url" : "https://api.github.com/users/fanquake/received_events",
      "repos_url" : "https://api.github.com/users/fanquake/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/fanquake"
   },
   "comments" : 1,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/21963/comments",
   "created_at" : "2021-05-16T18:06:14Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/21963/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/21963",
   "id" : 892725607,
   "labels" : [
      {
         "color" : "FBBAAB",
         "default" : false,
         "description" : null,
         "id" : 64585,
         "name" : "Bug",
         "node_id" : "MDU6TGFiZWw2NDU4NQ==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/21963/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "MDU6SXNzdWU4OTI3MjU2MDc=",
   "number" : 21963,
   "performed_via_github_app" : null,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "Intermittent CI failure: p2p_compactblocks.py - wait_until() failed",
   "updated_at" : "2021-05-17T00:35:54Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/21963",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/7826565?v=4",
      "events_url" : "https://api.github.com/users/practicalswift/events{/privacy}",
      "followers_url" : "https://api.github.com/users/practicalswift/followers",
      "following_url" : "https://api.github.com/users/practicalswift/following{/other_user}",
      "gists_url" : "https://api.github.com/users/practicalswift/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/practicalswift",
      "id" : 7826565,
      "login" : "practicalswift",
      "node_id" : "MDQ6VXNlcjc4MjY1NjU=",
      "organizations_url" : "https://api.github.com/users/practicalswift/orgs",
      "received_events_url" : "https://api.github.com/users/practicalswift/received_events",
      "repos_url" : "https://api.github.com/users/practicalswift/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/practicalswift/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/practicalswift/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/practicalswift"
   }
}
